// Italian Recipes
const recipes = {
    "Fruit Salad": ["Banana (1 medium)", "Apple (1 medium)", "Strawberries (1 cup sliced)"],
    "Greek Yogurt Parfait": ["Greek Yogurt (1 cup)", "Honey (1 tablespoon)", "Granola Bar (1 bar)"],
    "Veggie Omelette": ["Egg (1 large)", "Spinach (1 cup cooked)", "Carrot (1 medium)"],
    "Avocado Toast": ["Bread (1 slice)", "Avocado (1/2 medium)", "Egg (1 large)"],
    "Protein Smoothie": ["Milk (1 cup)", "Banana (1 medium)", "Peanut Butter (2 tablespoons)"],
    "Mixed Vegetable Stir-fry": ["Broccoli (1 cup chopped)", "Carrot (1 medium)", "Cauliflower (1 cup)"],
    "Chocolate Peanut Butter Smoothie": ["Soy Milk (1 cup)", "Peanut Butter (2 tablespoons)", "Cocoa 100% Powder (2 tbsp)"],
    "Oatmeal with Almonds": ["Oatmeal (1 cup cooked)", "Almonds (1 oz)", "Honey (1 tablespoon)"],
    "Tuna Salad": ["Tuna (3 oz canned in water)", "Spinach (1 cup cooked)", "Avocado (1/2 medium)"],
    "Quinoa Veggie Bowl": ["Quinoa (1 cup cooked)", "Mixed Vegetables (Cauliflower, Broccoli, Potatoes, Carrots, 1 cup)", "Avocado (1/2 medium)"],
    "Caprese Salad": ["Tomato (1 medium)", "Mozzarella (2 slices)", "Olive Oil (1 tablespoon)"],
    "Spaghetti Aglio e Olio": ["Pasta (1 cup cooked)", "Olive Oil (1 tablespoon)", "Garlic (2 cloves)"],
    "Bresaola Salad": ["Bresaola (3 oz)", "Arugula (1 cup)", "Parmesan (1 tbsp shavings)"],
    "Pasta al Pomodoro": ["Pasta (1 cup cooked)", "Tomato (1 medium)", "Olive Oil (1 tablespoon)"],
    "Parma Ham and Melon": ["Parma Ham (3 oz)", "Melon (1 cup sliced)"],
    "Pizza Margherita": ["Pizza Dough", "Tomato (1 medium)", "Mozzarella (1/2 cup)", "Basil (1 tbsp)", "Olive Oil (1 tablespoon)"],
    "Snizzer with Potatoes": ["80% Lean Meat (3 oz)", "Potatoes (1 medium)", "Olive Oil (1 tablespoon)", "Bread (1 slice)"],
    "Arancini": ["Rice (1 cup cooked)", "Mozzarella (1/2 cup)", "Bread (1 slice)", "Olive Oil (1 tablespoon)"],
    "Polpette (Meatballs)": ["80% Lean Meat (3 oz)", "Bread (1 slice)", "Egg (1 large)", "Onions (1/2 cup cooked)", "Olive Oil (1 tablespoon)"],
    "Casoncelli": ["Pasta (1 cup cooked)", "Ricotta (1/2 cup)", "Parma Ham (3 oz)", "Olive Oil (1 tablespoon)", "Butter (1 tbsp)"],
    "Classic American Burger": ["80% Lean Meat (3 oz)", "Bread (1 slice)", "Lettuce (1 cup)", "Tomato (1 medium)", "Onions (1/2 cup cooked)"],
    "Mac and Cheese": ["Pasta (1 cup cooked)", "Milk (1 cup)", "Cheddar Cheese (1/2 cup)", "Butter (1 tbsp)", "Bread (1 slice)"],
    "Thai Peanut Salad": ["Spinach (1 cup cooked)", "Peanut Butter (2 tablespoons)", "Soy Milk (1 cup)", "Carrot (1 medium)", "Cucumber (1 medium)"],
    "Indian Lentil Curry": ["Lentils (1 cup cooked)", "Onions (1/2 cup cooked)", "Tomato (1 medium)", "Garlic (2 cloves)", "Olive Oil (1 tablespoon)"],
    "Chickpea Tikka Masala": ["Chickpeas (1 cup cooked)", "Tomato (1 medium)", "Onions (1/2 cup cooked)", "Coconut Milk (1/2 cup)", "Olive Oil (1 tablespoon)"],
    "Pizza Quattro Formaggi": ["Pizza Dough", "Mozzarella (1/2 cup)", "Cheddar Cheese (1/4 cup)", "Stracciatella (1/4 cup)", "Fiocchi di Latte (Protein Mozzarella, 1/4 cup)", "Olive Oil (1 tablespoon)"],
    "Pasta Ragù": ["Pasta (1 cup cooked)", "80% Lean Meat (3 oz)", "Tomato (1 medium)", "Onions (1/2 cup cooked)", "Olive Oil (1 tablespoon)"],
    "Pasta Carbonara": ["Pasta (1 cup cooked)", "Egg (1 large)", "Parma Ham (3 oz)", "Olive Oil (1 tablespoon)", "Cheddar Cheese (1/4 cup)"]

};
